sudo: required
language: java

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=ezh1k/test
    - "TAG=$(if [ \"$TRAVIS_BRANCH\" == \"master\" ]; then echo \"latest\"; else echo $TRAVIS_BRANCH ; fi)"

services:
  - docker

before_script:
  - openssl aes-256-cbc -K "$encrypted_15c47f5577f9_key" -iv "$encrypted_15c47f5577f9_iv" -in .dockerhub.enc -out .dockerhub -d
  - sh .dockerhub
  - echo REPO:$REPO COMMIT:$COMMIT TAG:$TAG BUILD_NUMBER:$TRAVIS_BUILD_NUMBER

script:
  - docker images
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER

deploy:
  - docker images
  - docker push $REPO
